name             'bastion'
maintainer       'Riccardo Tacconi'
maintainer_email 'rtacconi@gmail.com'
license          'Smart421 All rights reserved'
description      'Installs/Configures bastion'
long_description 'Installs/Configures bastion, OpenSSH, updates kernel and security updates.'
version          '0.1.0'
